### ISSUE TITLE
Training on dsprites fails with 0-dim tensor

### ISSUE THREAD

**Issue by rcnlee** [1Konny/Beta-VAE#12]
I'm running ./run_dsprites_B_gamma100_z10.sh with a reduced number of iterations.
Error is below:

```python
=> no checkpoint found at 'checkpoints/dsprites_B_gamma100_z10/last'
 67%|██████████████████████████████████████████████████                         | 10000/15000.0 [34:22<16:59,  4.91it/s]Traceback (most recent call last):
  File "main.py", line 69, in <module>
    main(args)
  File "main.py", line 24, in main
    net.train()
  File "/Users/rlee18/git/Beta-VAE/solver.py", line 182, in train
    self.global_iter, recon_loss.data[0], total_kld.data[0], mean_kld.data[0]))
IndexError: invalid index of a 0-dim tensor. Use tensor.item() to convert a 0-dim tensor to a Python number
```

**Comment by Everbeast** [comment]
have you solved that problem?

**Comment by rcnlee** [comment]
No, I didn't solve it.

**Comment by lucasc896** [comment]
This should do it:

https://gist.github.com/lucasc896/017088d990980c43adec0af2dcb1c45c

**Comment by thavlik** [comment]
I can confirm the above changes remedy the problem. Thanks!
