### ISSUE TITLE
TypeError: save_image() got an unexpected keyword argument 'filename'

### ISSUE THREAD

**Issue by supershiye** [1Konny/Beta-VAE#18]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ye/anaconda3/envs/Pytorch/lib/python3.8/site-packages/visdom/__init__.py", line 708, in _send
    return self._handle_post(
  File "/home/ye/anaconda3/envs/Pytorch/lib/python3.8/site-packages/visdom/__init__.py", line 677, in _handle_post
    r = self.session.post(url, data=data)
  File "/home/ye/anaconda3/envs/Pytorch/lib/python3.8/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/ye/anaconda3/envs/Pytorch/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ye/anaconda3/envs/Pytorch/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/ye/anaconda3/envs/Pytorch/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23720d29d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Traceback (most recent call last):
  File "main.py", line 69, in <module>
    main(args)
  File "main.py", line 24, in main
    net.train()
  File "/home/ye/python_scripts/Beta-VAE-master/solver.py", line 201, in train
    self.viz_traverse()
  File "/home/ye/python_scripts/Beta-VAE-master/solver.py", line 417, in viz_traverse
    save_image(tensor=gifs[i][j].cpu(),
TypeError: save_image() got an unexpected keyword argument 'filename'
  1%|▏                              | 10000/1500000.0 [03:54<9:41:25, 42.71it/s]

**Comment by C-monC** [comment]
Change "filename" to "fp"
